MOSZE Task 3: Fighter Class Reference
Fighter Class Reference
#include <Fighter.h>
Public Member Functions
Fighter (const std::string &iname, double ihp, int idmg, double acd)
~Fighter ()
double getHP () const
double getDMG () const
double getCD () const
int getLVL () const
int getXP () const
std::string getName () const
Fighter & duel (Fighter *enemy)
Friends
std::ostream & operator<< (std::ostream &os, const Fighter &fi)
Detailed Description
Definition at line 13 of file Fighter.h.
Constructor & Destructor Documentation
Fighter()
Fighter::Fighter (const std::string & iname, double ihp, int idmg, double acd) inline
Definition at line 57 of file Fighter.h.
~Fighter()
Fighter::~Fighter () inline
Definition at line 58 of file Fighter.h.
Member Function Documentation
duel()
Fighter & Fighter::duel (Fighter * enemy)
Method for 2 characters fighting.
Definition at line 36 of file Fighter.cpp.
References getCD(), and getHP().
Referenced by getName(), and main().
getCD()
double Fighter::getCD () const inline
Definition at line 63 of file Fighter.h.
Referenced by duel().
getDMG()
double Fighter::getDMG () const inline
Definition at line 62 of file Fighter.h.
Referenced by operator<<().
getHP()
double Fighter::getHP () const inline
Definition at line 61 of file Fighter.h.
Referenced by duel(), main(), and operator<<().
getLVL()
int Fighter::getLVL () const inline
Definition at line 64 of file Fighter.h.
getName()
std::string Fighter::getName () const inline
Definition at line 67 of file Fighter.h.
References duel(), and operator<<.
Referenced by main(), and operator<<().
getXP()
int Fighter::getXP () const inline
Definition at line 65 of file Fighter.h.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Fighter & fi) friend
Operator overload to make the class printable.
Referenced by getName().
The documentation for this class was generated from the following files:
Fighter.h
Fighter.cpp