MOSZE Task 3: Jsonparser Class Reference
Jsonparser Class Reference
#include <Jsonparser.h>
Public Member Functions
~Jsonparser ()
Jsonparser ()
Static Public Member Functions
static std::map< std::string, std::string > getmap (std::string str)
static std::map< std::string, std::string > parseJson (std::string fname)
static std::map< std::string, std::string > parseJson (std::istream &input)
Detailed Description
Definition at line 4 of file Jsonparser.h.
Constructor & Destructor Documentation
~Jsonparser()
Jsonparser::~Jsonparser () inline
Definition at line 26 of file Jsonparser.h.
Jsonparser()
Jsonparser::Jsonparser () inline
Definition at line 27 of file Jsonparser.h.
Member Function Documentation
getmap()
std::map< std::string, std::string > Jsonparser::getmap (std::string str) static
Method that creates the map of a given string, that is in a json format.
Definition at line 18 of file Jsonparser.cpp.
Referenced by parseJson().
parseJson() [1/2]
std::map< std::string, std::string > Jsonparser::parseJson (std::string fname) static
Method that processes a json file that is given by its name.
Definition at line 84 of file Jsonparser.cpp.
References getmap().
Referenced by main().
parseJson() [2/2]
std::map< std::string, std::string > Jsonparser::parseJson (std::istream & input) static
Method that processes a json file that is given through an istream.
Definition at line 106 of file Jsonparser.cpp.
References getmap().
The documentation for this class was generated from the following files:
Jsonparser.h
Jsonparser.cpp