name: cppcheck

on:
  push
jobs:
  codec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing cppcheck
        run: sudo apt-get install cppcheck 
      - name: Permission
        run: chmod a+x ./cppcheck.sh
      - name: Code analysis
        run: ./cppcheck.sh
      - name: Artifact performance
        uses: actions/upload-artifact@v2
        with:
          path: ./performance_warnings.txt
      - name: Artifact style
        uses: actions/upload-artifact@v2
        with:
          path: ./style_warnings.txt
          
