name: cppcheck

on:
  push
jobs:
  codec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing cppcheck
        run: sudo apt-get install cppcheck 
      - name: Code analysis
        run: make cppcheck
      - name: Artifact performance-style
        uses: actions/upload-artifact@v2
        with:
          path: ./cppcheck_performance.txt


          
