name: Test workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: g++ -std=c++17 *.cpp
      - name: Permission
        run: chmod u+r+x test.sh
      - name: Run test
        run: ./test.sh
      - name: Diffy
        run: diff --strip-trailing-cr output.txt exp_output.txt
